// Generated by Xata Codegen 0.29.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "user",
    columns: [
      { name: "email", type: "email", unique: true },
      { name: "name", type: "string" },
      { name: "password", type: "string" },
    ],
  },
  {
    name: "blog",
    columns: [
      { name: "title", type: "string" },
      { name: "para", type: "text" },
      { name: "summery", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type User = InferredTypes["user"];
export type UserRecord = User & XataRecord;

export type Blog = InferredTypes["blog"];
export type BlogRecord = Blog & XataRecord;

export type DatabaseSchema = {
  user: UserRecord;
  blog: BlogRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://rajiWanigasingha-s-workspace-27u08g.eu-west-1.xata.sh/db/blog",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
